USE tienda;

SELECT nombre FROM producto;
SELECT nombre, precio FROM producto; 
SELECT * FROM producto;
SELECT nombre, precio AS 'precio EUR', precio * 1.04 AS 'precio USD' FROM producto;
SELECT nombre AS 'nombre de producto', precio AS 'EUR', (precio * 1.04) AS 'USD' FROM producto;
SELECT UPPER(nombre) AS nombre, precio FROM producto;
SELECT LOWER(nombre) AS nombre, precio FROM producto;
SELECT nombre, UPPER(SUBSTRING(nombre, 1, 2)) FROM fabricante;
SELECT nombre, ROUND(precio, 0) AS 'precio redondeado' FROM producto;
SELECT nombre, TRUNCATE(precio, 0) AS 'precio truncado' FROM producto;
SELECT f.codigo FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT DISTINCT f.codigo FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC; 
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3, 2;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre AS 'producto', p.precio AS 'precio', f.nombre AS 'fabricante' FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT f.nombre AS 'fabricante', p.nombre AS 'producto', p.precio AS 'precio' FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre ASC;
SELECT p.codigo AS 'codigo producto', p.nombre AS 'nombre producto', f.codigo AS 'codigo fabricante', f.nombre AS 'nombre fabricante' FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre AS 'nombre producto', p.precio, f.nombre AS 'nombre fabricante' FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY p.precio ASC LIMIT 1;
SELECT p.nombre AS 'nombre producto', p.precio, f.nombre AS 'nombre fabricante' FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY p.precio DESC LIMIT 1;
SELECT p.nombre, f.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo';
SELECT p.nombre AS 'producto' , f.nombre AS 'fabricante', p.precio FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Crucial' AND p.precio > 200;
SELECT p.nombre AS 'producto', f.nombre AS 'fabricante' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate';
SELECT p.nombre AS 'producto', f.nombre AS 'fabricante' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre IN('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre AS 'producto', p.precio AS 'precio', f.nombre AS 'fabricante' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre LIKE '%e';
SELECT p.nombre AS 'producto', p.precio AS 'precio', f.nombre AS 'fabricante' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre LIKE '%w%';
SELECT p.nombre AS 'producto', p.precio AS 'precio', f.nombre AS 'fabricante' FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
SELECT DISTINCT f.codigo AS 'codigo fabricante', f.nombre AS 'fabricante' FROM fabricante f INNER JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT f.nombre AS 'fabricante', p.nombre AS 'producto' FROM fabricante f LEFT JOIN producto p ON p.codigo_fabricante = f.codigo;
SELECT f.nombre AS 'fabricante' FROM fabricante f WHERE f.codigo NOT IN (SELECT f.codigo FROM fabricante f INNER JOIN producto p ON p.codigo_fabricante = f.codigo);
SELECT p.nombre AS 'producto' FROM producto p WHERE p.codigo_fabricante = (SELECT f.codigo FROM fabricante f WHERE f.nombre = 'Lenovo');
SELECT * FROM producto p WHERE p.codigo_fabricante = (SELECT f.codigo FROM fabricante f WHERE f.nombre = 'Lenovo') ORDER BY p.precio DESC LIMIT 1;
SELECT p.nombre AS 'producto caro Lenovo', p.precio AS 'precio' FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo' ORDER BY p.precio DESC LIMIT 1;
SELECT p.nombre AS 'producto barato HP', p.precio AS 'precio' FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Hewlett-Packard' ORDER BY p.precio ASC LIMIT 1;
SELECT p.nombre AS 'productos' FROM producto p WHERE p.precio >= (SELECT p.precio FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo' ORDER BY p.precio DESC LIMIT 1);
SELECT p.nombre AS 'producto', p.precio AS 'precio', f.nombre AS 'fabricante' FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus' AND p.precio > (SELECT AVG(p.precio) FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus');
 